/** 句子成分：主谓宾定状补 */
export type SentenceRole =
  | 'subject'
  | 'predicate'
  | 'object'
  | 'attributive'
  | 'adverbial'
  | 'complement'

export const SENTENCE_ROLE_LABELS: Record<SentenceRole, string> = {
  subject: '主语',
  predicate: '谓语',
  object: '宾语',
  attributive: '定语',
  adverbial: '状语',
  complement: '补语',
}

export interface SentenceTemplate {
  sentence: string
  sentenceZh: string
  answer: string
  distractors: string[]
  role: SentenceRole
  structureNote: string
  hint: string
}

export interface SentenceLevelTemplates {
  levelId: string
  templates: SentenceTemplate[]
}

export const SENTENCE_LEVEL_TEMPLATES: SentenceLevelTemplates[] = [
  {
    levelId: 'struct-1',
    templates: [
      {
        sentence: 'Tom {blank} football every Sunday.',
        sentenceZh: '汤姆每个星期天踢足球。',
        answer: 'plays',
        distractors: ['play', 'played', 'playing'],
        role: 'predicate',
        structureNote: '主语 Tom + 谓语 plays + 宾语 football',
        hint: '主语是第三人称单数 Tom，一般现在时谓语动词要加 -s。',
      },
      {
        sentence: 'My sister {blank} a new bike yesterday.',
        sentenceZh: '我姐姐昨天买了一辆新自行车。',
        answer: 'bought',
        distractors: ['buy', 'buys', 'buying'],
        role: 'predicate',
        structureNote: '主语 My sister + 谓语 bought + 宾语 a new bike',
        hint: 'yesterday 表示过去，谓语用 buy 的过去式 bought。',
      },
      {
        sentence: 'We {blank} English in the classroom.',
        sentenceZh: '我们在教室里学英语。',
        answer: 'study',
        distractors: ['studies', 'studied', 'studying'],
        role: 'predicate',
        structureNote: '主语 We + 谓语 study + 宾语 English',
        hint: '主语 We 是复数，一般现在时谓语用动词原形 study。',
      },
      {
        sentence: 'The cat {blank} milk on the table.',
        sentenceZh: '猫喝了桌上的牛奶。',
        answer: 'drank',
        distractors: ['drink', 'drinks', 'drinking'],
        role: 'predicate',
        structureNote: '主语 The cat + 谓语 drank + 宾语 milk',
        hint: '描述已完成的动作，用 drink 的过去式 drank。',
      },
      {
        sentence: 'I {blank} my homework after dinner.',
        sentenceZh: '晚饭后我做作业。',
        answer: 'do',
        distractors: ['does', 'did', 'doing'],
        role: 'predicate',
        structureNote: '主语 I + 谓语 do + 宾语 my homework',
        hint: '主语 I 搭配一般现在时，谓语用动词原形 do。',
      },
      {
        sentence: 'She {blank} a letter to her friend.',
        sentenceZh: '她给朋友写了一封信。',
        answer: 'wrote',
        distractors: ['write', 'writes', 'writing'],
        role: 'predicate',
        structureNote: '主语 She + 谓语 wrote + 宾语 a letter',
        hint: '写信是已完成的动作，谓语用 write 的过去式 wrote。',
      },
    ],
  },
  {
    levelId: 'struct-2',
    templates: [
      {
        sentence: 'It is a {blank} day. Let us go hiking.',
        sentenceZh: '今天天气晴朗，我们去徒步吧。',
        answer: 'sunny',
        distractors: ['sun', 'sunshine', 'sunnily'],
        role: 'attributive',
        structureNote: '定语 sunny 修饰名词 day：a sunny day',
        hint: '修饰名词 day 要用形容词 sunny（晴朗的），不能用副词 sunnily。',
      },
      {
        sentence: 'She wore a {blank} dress to the party.',
        sentenceZh: '她穿了一条漂亮的裙子去参加聚会。',
        answer: 'beautiful',
        distractors: ['beauty', 'beautifully', 'beautify'],
        role: 'attributive',
        structureNote: '定语 beautiful 修饰 dress：a beautiful dress',
        hint: '定语放在名词前，用形容词 beautiful 描述裙子。',
      },
      {
        sentence: 'The {blank} boy runs fastest in our class.',
        sentenceZh: '那个高个男孩是我们班跑得最快的。',
        answer: 'tall',
        distractors: ['tallly', 'height', 'taller'],
        role: 'attributive',
        structureNote: '定语 tall 修饰 boy：the tall boy',
        hint: '修饰名词 boy 用形容词 tall，表示「高的」。',
      },
      {
        sentence: 'We live in a {blank} house near the river.',
        sentenceZh: '我们住在河边一座安静的房子里。',
        answer: 'quiet',
        distractors: ['quietly', 'quietness', 'quieter'],
        role: 'attributive',
        structureNote: '定语 quiet 修饰 house：a quiet house',
        hint: '修饰名词 house 用形容词 quiet（安静的）。',
      },
      {
        sentence: 'He bought three {blank} apples.',
        sentenceZh: '他买了三个红苹果。',
        answer: 'red',
        distractors: ['redly', 'redden', 'reds'],
        role: 'attributive',
        structureNote: '定语 red 修饰 apples：three red apples',
        hint: '颜色词 red 作定语直接放在名词 apples 前。',
      },
      {
        sentence: 'This is an {blank} story for children.',
        sentenceZh: '这是一个有趣的儿童故事。',
        answer: 'interesting',
        distractors: ['interest', 'interested', 'interestingly'],
        role: 'attributive',
        structureNote: '定语 interesting 修饰 story',
        hint: 'story 令人有趣，用 -ing 形容词 interesting。',
      },
    ],
  },
  {
    levelId: 'struct-3',
    templates: [
      {
        sentence: 'She speaks English {blank}.',
        sentenceZh: '她英语说得很流利。',
        answer: 'fluently',
        distractors: ['fluent', 'fluency', 'more fluent'],
        role: 'adverbial',
        structureNote: '状语 fluently 修饰谓语 speaks（说得怎么样）',
        hint: '修饰动词 speaks 要用副词 fluently，不能用形容词 fluent。',
      },
      {
        sentence: 'Please walk {blank} in the library.',
        sentenceZh: '请在图书馆里安静地走。',
        answer: 'quietly',
        distractors: ['quiet', 'quietness', 'quieter'],
        role: 'adverbial',
        structureNote: '状语 quietly 修饰谓语 walk',
        hint: '修饰动词 walk 用副词 quietly（安静地）。',
      },
      {
        sentence: 'Tom runs very {blank} in the race.',
        sentenceZh: '汤姆在比赛中跑得很快。',
        answer: 'fast',
        distractors: ['fastly', 'faster', 'fastest'],
        role: 'adverbial',
        structureNote: '状语 fast 修饰谓语 runs',
        hint: 'fast 既可作形容词也可作副词，此处修饰 runs。',
      },
      {
        sentence: 'They worked {blank} to finish the project.',
        sentenceZh: '他们努力工作以完成项目。',
        answer: 'hard',
        distractors: ['hardly', 'harder', 'hardest'],
        role: 'adverbial',
        structureNote: '状语 hard 修饰谓语 worked（努力地）',
        hint: 'hard 作副词表示「努力地」；hardly 意思是「几乎不」。',
      },
      {
        sentence: 'The baby slept {blank} all night.',
        sentenceZh: '宝宝整夜睡得很安稳。',
        answer: 'soundly',
        distractors: ['sound', 'sounding', 'sounds'],
        role: 'adverbial',
        structureNote: '状语 soundly 修饰谓语 slept',
        hint: '修饰动词 slept 用副词 soundly（安稳地）。',
      },
      {
        sentence: 'He answered the question {blank}.',
        sentenceZh: '他正确地回答了问题。',
        answer: 'correctly',
        distractors: ['correct', 'correction', 'correctness'],
        role: 'adverbial',
        structureNote: '状语 correctly 修饰谓语 answered',
        hint: '修饰动词 answered 用副词 correctly。',
      },
    ],
  },
  {
    levelId: 'tense-1',
    templates: [
      {
        sentence: 'Look! The children {blank} in the park now.',
        sentenceZh: '看！孩子们现在正在公园里玩。',
        answer: 'are playing',
        distractors: ['play', 'played', 'will play'],
        role: 'predicate',
        structureNote: 'now 提示现在进行时：am/is/are + doing',
        hint: 'now 表示此刻正在发生，用 are playing。',
      },
      {
        sentence: 'I {blank} to Beijing last summer.',
        sentenceZh: '我去年夏天去了北京。',
        answer: 'went',
        distractors: ['go', 'goes', 'will go'],
        role: 'predicate',
        structureNote: 'last summer 提示一般过去时',
        hint: 'last summer 是过去时间，谓语用 go 的过去式 went。',
      },
      {
        sentence: 'We {blank} a picnic next Sunday.',
        sentenceZh: '我们下周日要去野餐。',
        answer: 'will have',
        distractors: ['have', 'had', 'are having'],
        role: 'predicate',
        structureNote: 'next Sunday 提示一般将来时：will + 动词原形',
        hint: 'next Sunday 表将来，用 will have。',
      },
      {
        sentence: 'She usually {blank} up at six.',
        sentenceZh: '她通常六点起床。',
        answer: 'gets',
        distractors: ['get', 'got', 'getting'],
        role: 'predicate',
        structureNote: 'usually 提示一般现在时，主语 She 需加 -s',
        hint: 'usually 表习惯，主语 She 用 gets。',
      },
      {
        sentence: 'They {blank} TV when I called.',
        sentenceZh: '我打电话时他们正在看电视。',
        answer: 'were watching',
        distractors: ['watch', 'watched', 'are watching'],
        role: 'predicate',
        structureNote: 'when I called 提示过去进行时',
        hint: '一个动作正在进行时另一个动作发生，用 were watching。',
      },
      {
        sentence: 'It {blank} every day in spring here.',
        sentenceZh: '这里春天每天都下雨。',
        answer: 'rains',
        distractors: ['rain', 'rained', 'is raining'],
        role: 'predicate',
        structureNote: 'every day 提示一般现在时',
        hint: 'every day 表经常性，主语 It 用 rains。',
      },
    ],
  },
  {
    levelId: 'tense-2',
    templates: [
      {
        sentence: 'I {blank} this book twice.',
        sentenceZh: '这本书我已经读过两遍了。',
        answer: 'have read',
        distractors: ['read', 'am reading', 'was reading'],
        role: 'predicate',
        structureNote: 'twice 与现在完成时连用，强调经历',
        hint: '强调已完成的经历用 have read。',
      },
      {
        sentence: 'She {blank} here since 2020.',
        sentenceZh: '她从 2020 年起一直在这里工作。',
        answer: 'has worked',
        distractors: ['works', 'worked', 'is working'],
        role: 'predicate',
        structureNote: 'since + 时间点 → 现在完成时',
        hint: 'since 2020 表从过去持续到现在的动作，用 has worked。',
      },
      {
        sentence: 'By the time we arrived, the film {blank}.',
        sentenceZh: '我们到达时电影已经开始了。',
        answer: 'had started',
        distractors: ['started', 'has started', 'starts'],
        role: 'predicate',
        structureNote: '过去的过去 → 过去完成时 had + 过去分词',
        hint: '到达之前电影已开始，用 had started。',
      },
      {
        sentence: 'He {blank} for an hour when I met him.',
        sentenceZh: '我见到他时他已经等了一小时。',
        answer: 'had waited',
        distractors: ['waited', 'has waited', 'waits'],
        role: 'predicate',
        structureNote: '见面之前已等待 → 过去完成时',
        hint: '见到之前已在等，用 had waited。',
      },
      {
        sentence: 'We {blank} never been to Shanghai.',
        sentenceZh: '我们从未去过上海。',
        answer: 'have',
        distractors: ['has', 'had', 'are'],
        role: 'predicate',
        structureNote: 'never been → have/has + 过去分词',
        hint: '主语 We 搭配 have never been。',
      },
      {
        sentence: 'The train {blank} by the time we got to the station.',
        sentenceZh: '我们到车站时火车已经开走了。',
        answer: 'had left',
        distractors: ['left', 'has left', 'leaves'],
        role: 'predicate',
        structureNote: '到车站之前火车已离开 → 过去完成时',
        hint: '到达之前火车已离开，用 had left。',
      },
    ],
  },
  {
    levelId: 'tense-3',
    templates: [
      {
        sentence: 'My brother {blank} to school by bike every day.',
        sentenceZh: '我哥哥每天骑自行车上学。',
        answer: 'goes',
        distractors: ['go', 'went', 'going'],
        role: 'predicate',
        structureNote: '第三人称单数 + 一般现在时 → goes',
        hint: '主语 My brother 是第三人称单数，谓语加 -es：goes。',
      },
      {
        sentence: 'She {blank} her teeth before breakfast.',
        sentenceZh: '她早饭前刷牙。',
        answer: 'brushes',
        distractors: ['brush', 'brushed', 'brushing'],
        role: 'predicate',
        structureNote: '第三人称单数 She → brushes',
        hint: 'brush 以 sh 结尾，第三人称单数加 -es。',
      },
      {
        sentence: 'They {blank} a great time at the party last night.',
        sentenceZh: '他们昨晚在聚会上玩得很开心。',
        answer: 'had',
        distractors: ['have', 'has', 'having'],
        role: 'predicate',
        structureNote: 'last night → 过去式 had',
        hint: 'have a great time 的过去式是 had a great time。',
      },
      {
        sentence: 'He {blank} his homework and went out.',
        sentenceZh: '他做完作业后出去了。',
        answer: 'finished',
        distractors: ['finish', 'finishes', 'finishing'],
        role: 'predicate',
        structureNote: 'and went 提示两个并列的过去动作',
        hint: '与 went 并列，前面也用过去式 finished。',
      },
      {
        sentence: 'The baby {blank} when we entered the room.',
        sentenceZh: '我们进房间时宝宝正在哭。',
        answer: 'was crying',
        distractors: ['cried', 'cries', 'is crying'],
        role: 'predicate',
        structureNote: 'when we entered 提示过去进行时',
        hint: '进入房间时正在哭，用 was crying。',
      },
      {
        sentence: 'Lucy {blank} the window because it was hot.',
        sentenceZh: '因为太热，露西打开了窗户。',
        answer: 'opened',
        distractors: ['open', 'opens', 'opening'],
        role: 'predicate',
        structureNote: 'because it was hot 提示过去原因',
        hint: 'was 是过去时，主句也用过去式 opened。',
      },
    ],
  },
  {
    levelId: 'adv-time',
    templates: [
      {
        sentence: 'I will call you {blank}.',
        sentenceZh: '我明天给你打电话。',
        answer: 'tomorrow',
        distractors: ['yesterday', 'now', 'always'],
        role: 'adverbial',
        structureNote: '时间状语 tomorrow 修饰 will call',
        hint: 'will 表将来，时间状语用 tomorrow（明天）。',
      },
      {
        sentence: 'She finished her work {blank} and went home.',
        sentenceZh: '她早早完成了工作回家了。',
        answer: 'early',
        distractors: ['earlier', 'earliest', 'earliness'],
        role: 'adverbial',
        structureNote: '时间状语 early 修饰 finished',
        hint: '修饰动词 finished 用副词 early（早早地）。',
      },
      {
        sentence: 'We have math class {blank} Monday morning.',
        sentenceZh: '我们每周一上午有数学课。',
        answer: 'every',
        distractors: ['each', 'all', 'always'],
        role: 'adverbial',
        structureNote: 'every Monday morning 表周期性时间',
        hint: 'every + 星期几 表示「每个……」，表频率。',
      },
      {
        sentence: 'He has lived here {blank} five years.',
        sentenceZh: '他在这里住了五年了。',
        answer: 'for',
        distractors: ['since', 'during', 'in'],
        role: 'adverbial',
        structureNote: 'for + 时间段，与完成时连用',
        hint: 'for five years 表持续五年，搭配完成时。',
      },
      {
        sentence: 'I saw him {blank} in the afternoon.',
        sentenceZh: '我昨天下午看见了他。',
        answer: 'yesterday',
        distractors: ['tomorrow', 'today', 'tonight'],
        role: 'adverbial',
        structureNote: 'yesterday afternoon 表过去时间',
        hint: 'saw 是过去式，时间状语用 yesterday。',
      },
      {
        sentence: 'The shop opens {blank} nine o\'clock.',
        sentenceZh: '商店九点开门。',
        answer: 'at',
        distractors: ['on', 'in', 'by'],
        role: 'adverbial',
        structureNote: 'at + 具体时刻 作时间状语',
        hint: '具体钟点用 at：at nine o\'clock。',
      },
    ],
  },
  {
    levelId: 'adv-place',
    templates: [
      {
        sentence: 'There are many books {blank} the shelf.',
        sentenceZh: '书架上有许多书。',
        answer: 'on',
        distractors: ['in', 'at', 'to'],
        role: 'adverbial',
        structureNote: '地点状语 on the shelf 表位置',
        hint: '书在架子「上面」，用 on。',
      },
      {
        sentence: 'We waited for the bus {blank} the station.',
        sentenceZh: '我们在车站等公交车。',
        answer: 'at',
        distractors: ['on', 'in', 'to'],
        role: 'adverbial',
        structureNote: 'at the station 表地点',
        hint: '车站这类地点用 at the station。',
      },
      {
        sentence: 'The keys are {blank} your bag.',
        sentenceZh: '钥匙在你包里。',
        answer: 'in',
        distractors: ['on', 'at', 'under'],
        role: 'adverbial',
        structureNote: 'in your bag 表在……里面',
        hint: '在包「里面」用 in。',
      },
      {
        sentence: 'Please put the chair {blank} the desk.',
        sentenceZh: '请把椅子放在书桌下面。',
        answer: 'under',
        distractors: ['on', 'in', 'behind'],
        role: 'adverbial',
        structureNote: 'under the desk 表地点状语',
        hint: '在书桌「下面」用 under。',
      },
      {
        sentence: 'They walked {blank} the river after school.',
        sentenceZh: '放学后他们沿着河走。',
        answer: 'along',
        distractors: ['across', 'through', 'into'],
        role: 'adverbial',
        structureNote: 'along the river 表沿着……',
        hint: '沿着河走用 along the river。',
      },
      {
        sentence: 'The cat hid {blank} the sofa.',
        sentenceZh: '猫躲在沙发后面。',
        answer: 'behind',
        distractors: ['before', 'beside', 'above'],
        role: 'adverbial',
        structureNote: 'behind the sofa 表地点',
        hint: '在沙发「后面」用 behind。',
      },
    ],
  },
  {
    levelId: 'adj-adv-1',
    templates: [
      {
        sentence: 'The soup tastes {blank}.',
        sentenceZh: '这汤尝起来很美味。',
        answer: 'delicious',
        distractors: ['deliciously', 'delight', 'delightful'],
        role: 'complement',
        structureNote: 'taste 是系动词，后接学者作表语/补语',
        hint: 'taste 此处是系动词「尝起来」，后接学者 delicious。',
      },
      {
        sentence: 'She looks {blank} in that red dress.',
        sentenceZh: '她穿那条红裙子很好看。',
        answer: 'beautiful',
        distractors: ['beautifully', 'beauty', 'beautify'],
        role: 'complement',
        structureNote: 'look 是系动词 + 学者 beautiful',
        hint: 'look 此处是「看起来」，后接学者 beautiful。',
      },
      {
        sentence: 'He drives too {blank}. Please be careful.',
        sentenceZh: '他开车太快了，请小心。',
        answer: 'fast',
        distractors: ['fastly', 'faster', 'fastest'],
        role: 'adverbial',
        structureNote: 'too fast 修饰动词 drives',
        hint: '修饰动词 drives 用魔法师 fast；too fast 表示「太快」。',
      },
      {
        sentence: 'The exam was surprisingly {blank}.',
        sentenceZh: '考试出乎意料地简单。',
        answer: 'easy',
        distractors: ['easily', 'ease', 'easier'],
        role: 'complement',
        structureNote: 'was + 学者 easy 作表语',
        hint: 'was 是系动词，后接学者 easy 作表语。',
      },
      {
        sentence: 'Please speak more {blank} so everyone can hear.',
        sentenceZh: '请大声说以便大家都能听到。',
        answer: 'loudly',
        distractors: ['loud', 'louder', 'aloud'],
        role: 'adverbial',
        structureNote: 'more loudly 修饰 speak',
        hint: '修饰动词 speak 用魔法师 loudly（大声地）。',
      },
      {
        sentence: 'I feel {blank} today because I slept well.',
        sentenceZh: '今天我感觉很好，因为我睡得很好。',
        answer: 'good',
        distractors: ['well', 'better', 'best'],
        role: 'complement',
        structureNote: 'feel 是系动词 + good 表状态',
        hint: 'feel 后接学者 good 表示「感觉好」；well 多作魔法师或「身体好」。',
      },
      {
        sentence: 'The music sounds {blank}.',
        sentenceZh: '这音乐听起来很动听。',
        answer: 'beautiful',
        distractors: ['beautifully', 'beauty', 'beautify'],
        role: 'complement',
        structureNote: 'sound 是系动词 + 学者 beautiful',
        hint: 'sound「听起来」后接学者 beautiful，不用 beautifully。',
      },
      {
        sentence: 'She danced {blank} at the party.',
        sentenceZh: '她在派对上舞跳得很优雅。',
        answer: 'gracefully',
        distractors: ['graceful', 'grace', 'gracious'],
        role: 'adverbial',
        structureNote: 'gracefully 修饰动词 danced',
        hint: '修饰动词 danced 用魔法师 gracefully（优雅地）。',
      },
      {
        sentence: 'The story sounded {blank}.',
        sentenceZh: '这个故事听起来很有趣。',
        answer: 'interesting',
        distractors: ['interestingly', 'interest', 'interested'],
        role: 'complement',
        structureNote: 'sound 系动词 + 学者 interesting',
        hint: 'sound 后接学者 interesting 描述故事本身。',
      },
      {
        sentence: 'Please write {blank} on the paper.',
        sentenceZh: '请在纸上认真书写。',
        answer: 'carefully',
        distractors: ['careful', 'careless', 'care'],
        role: 'adverbial',
        structureNote: 'carefully 修饰动词 write',
        hint: '修饰动词 write 用魔法师 carefully（认真地）。',
      },
      {
        sentence: 'The weather stayed {blank} all week.',
        sentenceZh: '整个星期天气一直很暖和。',
        answer: 'warm',
        distractors: ['warmly', 'warmth', 'warmer'],
        role: 'complement',
        structureNote: 'stay 系动词 + 学者 warm',
        hint: 'stay 表示持续状态，后接学者 warm。',
      },
      {
        sentence: 'He turned {blank} when he heard the news.',
        sentenceZh: '听到消息时他的脸变红了。',
        answer: 'red',
        distractors: ['redly', 'redden', 'reddish'],
        role: 'complement',
        structureNote: 'turn 系动词 + 学者 red',
        hint: 'turn 此处表「变成」，后接学者 red。',
      },
    ],
  },
  {
    levelId: 'adj-adv-2',
    templates: [
      {
        sentence: 'Tom is {blank} than his brother.',
        sentenceZh: '汤姆比他哥哥高。',
        answer: 'taller',
        distractors: ['tall', 'tallest', 'more tall'],
        role: 'complement',
        structureNote: 'than 提示比较级 taller',
        hint: 'than 表示比较，用 tall 的比较级 taller。',
      },
      {
        sentence: 'This is the {blank} book I have ever read.',
        sentenceZh: '这是我读过的最有趣的书。',
        answer: 'most interesting',
        distractors: ['more interesting', 'interesting', 'interestinger'],
        role: 'attributive',
        structureNote: 'the most interesting 表最高级',
        hint: 'ever read 与最高级连用：the most interesting。',
      },
      {
        sentence: 'She runs {blank} in our team.',
        sentenceZh: '她是我们队跑得最快的。',
        answer: 'fastest',
        distractors: ['faster', 'fast', 'more fast'],
        role: 'adverbial',
        structureNote: 'in our team 范围内最高级',
        hint: '在团队范围内比较，用魔法师最高级 fastest。',
      },
      {
        sentence: 'Winter is {blank} than autumn here.',
        sentenceZh: '这里的冬天比秋天更冷。',
        answer: 'colder',
        distractors: ['cold', 'coldest', 'more cold'],
        role: 'complement',
        structureNote: 'than → 比较级 colder',
        hint: 'cold 的比较级是 colder，不是 more cold。',
      },
      {
        sentence: 'He answered the questions {blank} of all.',
        sentenceZh: '他回答得所有人中最仔细。',
        answer: 'most carefully',
        distractors: ['more carefully', 'carefully', 'careful'],
        role: 'adverbial',
        structureNote: 'of all 提示魔法师最高级',
        hint: 'carefully 的最高级是 most carefully。',
      },
      {
        sentence: 'This box is {blank} than that one.',
        sentenceZh: '这个箱子比那个重。',
        answer: 'heavier',
        distractors: ['heavy', 'heaviest', 'more heavy'],
        role: 'complement',
        structureNote: 'than → 比较级 heavier',
        hint: 'heavy 以辅音+y 结尾，变比较级改 y 为 i 加 -er：heavier。',
      },
      {
        sentence: 'My room is {blank} than yours.',
        sentenceZh: '我的房间比你的大。',
        answer: 'bigger',
        distractors: ['big', 'biggest', 'more big'],
        role: 'complement',
        structureNote: 'than → 比较级 bigger',
        hint: 'than 提示比较级，big 的比较级是 bigger。',
      },
      {
        sentence: 'She is the {blank} student in our class.',
        sentenceZh: '她是我们班最优秀的学生。',
        answer: 'best',
        distractors: ['better', 'good', 'well'],
        role: 'attributive',
        structureNote: 'in our class 范围内最高级',
        hint: '在班级范围内比较，用 good 的最高级 best。',
      },
      {
        sentence: 'He works {blank} than anyone else.',
        sentenceZh: '他比任何人都更努力。',
        answer: 'harder',
        distractors: ['hard', 'hardest', 'more hard'],
        role: 'adverbial',
        structureNote: 'than → 副词比较级 harder',
        hint: '修饰动词 works，hard 的比较级是 harder。',
      },
      {
        sentence: 'This river is the {blank} in the country.',
        sentenceZh: '这条河是国内最长的。',
        answer: 'longest',
        distractors: ['longer', 'long', 'most long'],
        role: 'attributive',
        structureNote: 'in the country 提示最高级',
        hint: '在国内范围比较，用 long 的最高级 longest。',
      },
      {
        sentence: 'You should drive more {blank} in the rain.',
        sentenceZh: '雨天你应该开得更慢些。',
        answer: 'slowly',
        distractors: ['slow', 'slower', 'slowest'],
        role: 'adverbial',
        structureNote: 'more slowly 修饰动词 drive',
        hint: '修饰动词 drive 用魔法师 slowly；more slowly 是比较级。',
      },
      {
        sentence: 'Today is {blank} than yesterday.',
        sentenceZh: '今天比昨天更热。',
        answer: 'hotter',
        distractors: ['hot', 'hottest', 'more hot'],
        role: 'complement',
        structureNote: 'than → 比较级 hotter',
        hint: 'hot 以重读闭音节结尾，比较级双写 t 加 -er：hotter。',
      },
    ],
  },
]
